name: Update GitHub Pages Redirection

on:
  release:
    types: [published]
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  update-redirect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release asset URL
        id: get_url
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/McSon2/SSP_referal/releases/latest | grep browser_download_url | grep .exe | head -n 1 | cut -d '"' -f 4)
          echo "LATEST_URL=$LATEST_URL" >> $GITHUB_ENV

      - name: Generate index.html
        run: |
          mkdir -p deploy
          echo "<!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv=\"refresh\" content=\"0; url=${LATEST_URL}\" />
            <title>Redirection...</title>
          </head>
          <body>
            <p>Redirection en cours vers le téléchargement de la dernière version...</p>
          </body>
          </html>" > deploy/index.html

      - name: Verify index.html
        run: |
          echo "Contenu de deploy/index.html :"
          cat deploy/index.html
          echo "Liste des fichiers dans deploy :"
          ls -la deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy  # Pointage vers le répertoire dédié
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: "Mise à jour de la redirection vers la dernière release"
